import { useEffect, useState } from "react";
import { CalendarPlus, ClipboardCheck, Pencil, Trash2, UserRoundSearch } from "lucide-react";
import { toast } from "sonner";
import { StudentAnalytics } from "@/components/site/Analytics";
import { Avatar, Card, db } from "@/components/site/shared";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useApp } from "@/lib/app-context";

export function AdminPerformance() {
  const { tx } = useApp();
  const [students, setStudents] = useState<any[]>([]), [studentId, setStudentId] = useState(""), [absences, setAbsences] = useState<any[]>([]), [grades, setGrades] = useState<any[]>([]), [pending, setPending] = useState<any[]>([]), [reload, setReload] = useState(0);
  const [absence, setAbsence] = useState({ absence_date: new Date().toISOString().slice(0, 10), reason: "" });
  const blankGrade = { exam_title: "", score: 0, total: 100, exam_date: new Date().toISOString().slice(0, 10) };
  const [grade, setGrade] = useState(blankGrade), [editing, setEditing] = useState<string | null>(null);
  useEffect(() => { db.from("profiles").select("id,full_name,stage,avatar_url,status").eq("status", "approved").order("full_name").then(({ data }: any) => { setStudents(data ?? []); if (!studentId && data?.[0]) setStudentId(data[0].id); }); }, []);
  const load = async () => { if (!studentId) return; const [a, g, p] = await Promise.all([db.from("student_absences").select("*").eq("user_id", studentId).order("absence_date", { ascending: false }), db.from("center_grades").select("*").eq("user_id", studentId).order("exam_date", { ascending: false }), db.from("attempts").select("id,exam_id,score,total,objective_score,essay_score,grading_status,answers,exams(title)").eq("user_id", studentId).eq("grading_status", "pending")]); setAbsences(a.data ?? []); setGrades(g.data ?? []); setPending(p.data ?? []); setReload((x) => x + 1); };
  useEffect(() => { load(); }, [studentId]);
  const student = students.find((s) => s.id === studentId);
  const saveGrade = async () => { if (!grade.exam_title || grade.total <= 0 || grade.score < 0 || grade.score > grade.total) return toast.error(tx("راجع بيانات الدرجة", "Check grade values")); const payload = { ...grade, user_id: studentId }; const result = editing ? await db.from("center_grades").update(payload).eq("id", editing) : await db.from("center_grades").insert(payload); if (result.error) return toast.error(result.error.message); setGrade(blankGrade); setEditing(null); load(); };
  return <div className="space-y-5"><Card className="flex flex-wrap items-center gap-4 border-primary/30"><div className="icon-tile"><UserRoundSearch className="h-6 w-6" /></div><div className="min-w-52 flex-1"><Label>{tx("اختر الطالب", "Choose student")}</Label><select className="mt-1 h-11 w-full rounded-md border border-input bg-background px-3" value={studentId} onChange={(e) => setStudentId(e.target.value)}>{students.map((s) => <option key={s.id} value={s.id}>{s.full_name}</option>)}</select></div>{student && <div className="flex items-center gap-3"><Avatar path={student.avatar_url} size={48} /><strong>{student.full_name}</strong></div>}</Card>
    {studentId && <><div className="grid gap-4 xl:grid-cols-2"><Card><h3 className="mb-4 flex items-center gap-2 font-bold"><CalendarPlus className="text-primary" />{tx("تسجيل غياب", "Record absence")}</h3><div className="grid gap-2 sm:grid-cols-[160px_1fr_auto]"><Input type="date" value={absence.absence_date} onChange={(e) => setAbsence({ ...absence, absence_date: e.target.value })} /><Input placeholder={tx("السبب (اختياري)", "Reason (optional)")} value={absence.reason} onChange={(e) => setAbsence({ ...absence, reason: e.target.value })} /><Button onClick={async () => { await db.from("student_absences").insert({ ...absence, user_id: studentId }); setAbsence({ ...absence, reason: "" }); load(); }}>{tx("إضافة", "Add")}</Button></div><div className="mt-4 max-h-48 overflow-y-auto">{absences.map((a) => <div key={a.id} className="flex items-center gap-2 border-t py-2 text-sm"><span>{a.absence_date}</span><span className="flex-1 text-muted-foreground">{a.reason || "—"}</span><Button size="icon" variant="ghost" aria-label={tx("حذف", "Delete")} onClick={async () => { await db.from("student_absences").delete().eq("id", a.id); load(); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></div>)}</div></Card>
      <Card><h3 className="mb-4 flex items-center gap-2 font-bold"><ClipboardCheck className="text-primary" />{tx("درجات السنتر", "Center grades")}</h3><div className="grid gap-2 sm:grid-cols-2"><Input placeholder={tx("اسم الامتحان", "Exam name")} value={grade.exam_title} onChange={(e) => setGrade({ ...grade, exam_title: e.target.value })} /><Input type="date" value={grade.exam_date} onChange={(e) => setGrade({ ...grade, exam_date: e.target.value })} /><Input type="number" placeholder={tx("الدرجة", "Score")} value={grade.score} onChange={(e) => setGrade({ ...grade, score: +e.target.value })} /><Input type="number" placeholder={tx("النهاية", "Total")} value={grade.total} onChange={(e) => setGrade({ ...grade, total: +e.target.value })} /></div><Button className="mt-3" onClick={saveGrade}>{editing ? tx("حفظ التعديل", "Save changes") : tx("إضافة الدرجة", "Add grade")}</Button><div className="mt-4 max-h-52 overflow-y-auto">{grades.map((g) => <div key={g.id} className="flex items-center gap-2 border-t py-2 text-sm"><span className="flex-1">{g.exam_title} · {g.score}/{g.total} · {g.exam_date}</span><Button size="icon" variant="ghost" aria-label={tx("تعديل", "Edit")} onClick={() => { setEditing(g.id); setGrade({ exam_title: g.exam_title, score: Number(g.score), total: Number(g.total), exam_date: g.exam_date }); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" aria-label={tx("حذف", "Delete")} onClick={async () => { await db.from("center_grades").delete().eq("id", g.id); load(); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></div>)}</div></Card></div>
      {pending.length > 0 && <Card><h3 className="mb-4 font-bold text-primary">{tx("إجابات مقالية بانتظار التصحيح", "Essays awaiting grading")}</h3>{pending.map((attempt) => <EssayGrade key={attempt.id} attempt={attempt} done={load} />)}</Card>}
      <StudentAnalytics userId={studentId} stage={student?.stage} reloadKey={reload} /></>}
  </div>;
}

function EssayGrade({ attempt, done }: { attempt: any; done: () => void }) {
  const { tx } = useApp(); const [questions, setQuestions] = useState<any[]>([]), [score, setScore] = useState(0);
  useEffect(() => { db.from("questions").select("id,prompt,points,question_type").eq("exam_id", attempt.exam_id).eq("question_type", "essay").order("q_order").then(({ data }: any) => setQuestions(data ?? [])); }, [attempt.exam_id]);
  const max = questions.reduce((sum, q) => sum + q.points, 0);
  return <div className="mb-4 rounded-lg border border-primary/25 p-4"><h4 className="mb-3 font-bold">{attempt.exams?.title}</h4>{questions.map((q) => <div key={q.id} className="mb-3"><p className="text-sm font-semibold">{q.prompt} ({q.points})</p><p className="mt-1 rounded-md bg-muted p-3 text-sm">{String(attempt.answers?.[q.id] ?? tx("بدون إجابة", "No answer"))}</p></div>)}<div className="flex items-center gap-2"><Input className="w-28" type="number" min={0} max={max} value={score} onChange={(e) => setScore(+e.target.value)} /><span className="text-sm">/ {max}</span><Button onClick={async () => { if (score < 0 || score > max) return toast.error(tx("درجة غير صحيحة", "Invalid score")); const objective = Number(attempt.objective_score) || Number(attempt.score); await db.from("attempts").update({ essay_score: score, score: objective + score, grading_status: "graded" }).eq("id", attempt.id); done(); }}>{tx("اعتماد الدرجة", "Approve grade")}</Button></div></div>;
}