import { useEffect, useState } from "react";
import { FolderPlus, ImagePlus, LockKeyhole, Trash2, UploadCloud, Video } from "lucide-react";
import { toast } from "sonner";
import { Card, db } from "@/components/site/shared";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { STAGE_LABEL, STAGES, type Stage, uploadFile, uploadFileWithProgress, useApp, useSignedUrl } from "@/lib/app-context";

const selectClass = "h-10 w-full rounded-md border border-input bg-background px-3";
export function AdminLectures() {
  const { tx, lang } = useApp();
  const [folders, setFolders] = useState<any[]>([]), [videos, setVideos] = useState<any[]>([]), [folderStage, setFolderStage] = useState<Stage>("sec1"), [folderTitle, setFolderTitle] = useState("");
  const blank = { stage: "sec1" as Stage, folder_id: "", title: "", description: "", source: "youtube", url: "", is_locked: false, price: 0 };
  const [video, setVideo] = useState(blank), [videoFile, setVideoFile] = useState<File | null>(null), [cover, setCover] = useState<File | null>(null), [progress, setProgress] = useState(0), [busy, setBusy] = useState(false);
  const load = async () => { const [f, v] = await Promise.all([db.from("folders").select("*").order("created_at"), db.from("videos").select("*").order("created_at", { ascending: false })]); setFolders(f.data ?? []); setVideos(v.data ?? []); };
  useEffect(() => { load(); }, []);
  const add = async () => { if (!video.title) return toast.error(tx("اكتب عنوان المحاضرة", "Lecture title required")); setBusy(true); setProgress(0); try { let url = video.url; if (video.source === "upload") { if (!videoFile) throw new Error(tx("اختر ملف الفيديو", "Choose a video file")); url = await uploadFileWithProgress("videos", video.stage, videoFile, setProgress); } const cover_image_url = cover ? await uploadFile("media", `covers/${video.stage}`, cover) : null; const { error } = await db.from("videos").insert({ ...video, url, cover_image_url, folder_id: video.folder_id || null }); if (error) throw error; toast.success(tx("تمت إضافة المحاضرة", "Lecture added")); setVideo(blank); setVideoFile(null); setCover(null); setProgress(0); load(); } catch (error: any) { toast.error(error.message); } finally { setBusy(false); } };
  return <div className="space-y-5"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card><h3 className="mb-4 flex items-center gap-2 font-bold"><FolderPlus className="text-primary" />{tx("الوحدات الدراسية", "Study units")}</h3><select className={selectClass} value={folderStage} onChange={(e) => setFolderStage(e.target.value as Stage)}>{STAGES.map((stage) => <option key={stage} value={stage}>{STAGE_LABEL[stage][lang]}</option>)}</select><div className="mt-2 flex gap-2"><Input value={folderTitle} onChange={(e) => setFolderTitle(e.target.value)} placeholder={tx("اسم الوحدة", "Unit name")} /><Button onClick={async () => { if (!folderTitle) return; await db.from("folders").insert({ title: folderTitle, stage: folderStage }); setFolderTitle(""); load(); }}><FolderPlus className="h-4 w-4" /></Button></div><div className="mt-4 max-h-72 overflow-y-auto">{folders.map((folder) => <div key={folder.id} className="flex items-center gap-2 border-t py-2 text-sm"><span className="flex-1">{folder.title} · {STAGE_LABEL[folder.stage as Stage][lang]}</span><Button size="icon" variant="ghost" aria-label={tx("حذف", "Delete")} onClick={async () => { await db.from("folders").delete().eq("id", folder.id); load(); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></div>)}</div></Card>
    <Card className="space-y-3 border-primary/30"><h3 className="flex items-center gap-2 font-bold"><UploadCloud className="text-primary" />{tx("إضافة محاضرة", "Add lecture")}</h3><div className="grid gap-3 sm:grid-cols-2"><select className={selectClass} value={video.stage} onChange={(e) => setVideo({ ...video, stage: e.target.value as Stage, folder_id: "" })}>{STAGES.map((stage) => <option key={stage} value={stage}>{STAGE_LABEL[stage][lang]}</option>)}</select><select className={selectClass} value={video.folder_id} onChange={(e) => setVideo({ ...video, folder_id: e.target.value })}><option value="">{tx("بدون وحدة", "No unit")}</option>{folders.filter((f) => f.stage === video.stage).map((f) => <option key={f.id} value={f.id}>{f.title}</option>)}</select></div><Input placeholder={tx("عنوان المحاضرة", "Lecture title")} value={video.title} onChange={(e) => setVideo({ ...video, title: e.target.value })} /><Input placeholder={tx("وصف مختصر", "Short description")} value={video.description} onChange={(e) => setVideo({ ...video, description: e.target.value })} /><select className={selectClass} value={video.source} onChange={(e) => setVideo({ ...video, source: e.target.value })}><option value="youtube">YouTube</option><option value="external">{tx("رابط خارجي", "External link")}</option><option value="upload">{tx("رفع من الجهاز", "Device upload")}</option></select>{video.source === "upload" ? <Input type="file" accept="video/*" onChange={(e) => setVideoFile(e.target.files?.[0] ?? null)} /> : <Input placeholder="https://…" value={video.url} onChange={(e) => setVideo({ ...video, url: e.target.value })} />}<Label className="flex items-center gap-2"><ImagePlus className="h-4 w-4 text-primary" />{tx("صورة غلاف المحاضرة", "Lecture cover image")}</Label><Input type="file" accept="image/*" onChange={(e) => setCover(e.target.files?.[0] ?? null)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={video.is_locked} onChange={(e) => setVideo({ ...video, is_locked: e.target.checked, price: e.target.checked ? video.price : 0 })} /><LockKeyhole className="h-4 w-4 text-primary" />{tx("محاضرة مدفوعة بكود", "Paid lecture with code")}</label>{video.is_locked && <Input type="number" min="0" placeholder={tx("سعر الحصة", "Price")} value={video.price} onChange={(e) => setVideo({ ...video, price: +e.target.value })} />}{busy && video.source === "upload" && <div><div className="mb-1 flex justify-between text-xs"><span>{tx("جارٍ رفع الفيديو", "Uploading video")}</span><b>{progress}%</b></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-gold-gradient transition-all" style={{ width: `${progress}%` }} /></div></div>}<Button disabled={busy} onClick={add} className="w-full">{busy ? `${progress}%` : tx("نشر المحاضرة", "Publish lecture")}</Button></Card></div>
    <section><h3 className="mb-4 flex items-center gap-2 text-xl font-black"><Video className="text-primary" />{tx("المحاضرات المنشورة", "Published lectures")}</h3><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{videos.map((item) => <AdminVideoCard key={item.id} item={item} remove={async () => { await db.from("videos").delete().eq("id", item.id); load(); }} />)}</div></section></div>;
}

function AdminVideoCard({ item, remove }: { item: any; remove: () => void }) { const { tx } = useApp(); const cover = useSignedUrl("media", item.cover_image_url); return <Card className="overflow-hidden p-0"><div className="aspect-video bg-navy-deep">{cover ? <img src={cover} alt={item.title} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><Video className="h-12 w-12 text-primary/30" /></div>}</div><div className="flex items-start gap-3 p-4"><div className="flex-1"><h4 className="font-bold">{item.title}</h4><p className="mt-1 text-xs text-primary">{item.is_locked ? `${item.price} ${tx("جنيه", "EGP")}` : tx("مجاني", "Free")}</p></div><Button size="icon" variant="ghost" aria-label={tx("حذف", "Delete")} onClick={remove}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></Card>; }