import { useEffect, useState } from "react";
import { ClipboardPlus, FilePenLine, ListChecks, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Card, db } from "@/components/site/shared";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { STAGES, STAGE_LABEL, type Stage, uploadFile, useApp } from "@/lib/app-context";

const selectClass = "h-10 w-full rounded-md border border-input bg-background px-3";
export function AdminExams() {
  const { tx, lang } = useApp(); const [folders, setFolders] = useState<any[]>([]), [exams, setExams] = useState<any[]>([]), [editing, setEditing] = useState<any>(null); const [form, setForm] = useState({ stage: "sec1" as Stage, folder_id: "", title: "" });
  const load = async () => { const [f, e] = await Promise.all([db.from("folders").select("*").order("created_at"), db.from("exams").select("*").order("created_at", { ascending: false })]); setFolders(f.data ?? []); setExams(e.data ?? []); };
  useEffect(() => { load(); }, []); if (editing) return <QuestionEditor exam={editing} back={() => setEditing(null)} />;
  return <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><Card className="space-y-3 border-primary/30"><h3 className="flex items-center gap-2 font-bold"><ClipboardPlus className="text-primary" />{tx("إنشاء امتحان", "Create exam")}</h3><select className={selectClass} value={form.stage} onChange={(e) => setForm({ ...form, stage: e.target.value as Stage, folder_id: "" })}>{STAGES.map((s) => <option key={s} value={s}>{STAGE_LABEL[s][lang]}</option>)}</select><select className={selectClass} value={form.folder_id} onChange={(e) => setForm({ ...form, folder_id: e.target.value })}><option value="">{tx("بدون وحدة", "No unit")}</option>{folders.filter((f) => f.stage === form.stage).map((f) => <option key={f.id} value={f.id}>{f.title}</option>)}</select><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder={tx("اسم الامتحان", "Exam name")} /><Button className="w-full" onClick={async () => { if (!form.title) return; await db.from("exams").insert({ ...form, folder_id: form.folder_id || null }); setForm({ ...form, title: "" }); load(); }}>{tx("إنشاء وإضافة الأسئلة", "Create and add questions")}</Button></Card><div className="grid content-start gap-4 md:grid-cols-2">{exams.map((exam) => <Card key={exam.id} className="border-primary/25"><div className="mb-4 flex items-start gap-3"><div className="icon-tile"><ListChecks className="h-5 w-5" /></div><div className="flex-1"><h3 className="font-bold">{exam.title}</h3><p className="text-xs text-muted-foreground">{STAGE_LABEL[exam.stage as Stage][lang]}</p></div></div><div className="flex gap-2"><Button className="flex-1" variant="outline" onClick={() => setEditing(exam)}><FilePenLine className="h-4 w-4" />{tx("الأسئلة", "Questions")}</Button><Button variant={exam.is_closed ? "secondary" : "default"} onClick={async () => { await db.from("exams").update({ is_closed: !exam.is_closed }).eq("id", exam.id); load(); }}>{exam.is_closed ? tx("إعادة فتح", "Reopen") : tx("غلق", "Close")}</Button><Button size="icon" variant="ghost" aria-label={tx("حذف", "Delete")} onClick={async () => { if (!confirm(tx("حذف الامتحان؟", "Delete exam?"))) return; await db.from("attempts").delete().eq("exam_id", exam.id); await db.from("questions").delete().eq("exam_id", exam.id); await db.from("exams").delete().eq("id", exam.id); load(); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></Card>)}</div></div>;
}

function QuestionEditor({ exam, back }: { exam: any; back: () => void }) {
  const { tx } = useApp(); const [questions, setQuestions] = useState<any[]>([]), [image, setImage] = useState<File | null>(null); const blank = { prompt: "", question_type: "multiple_choice", points: 1, options: ["", "", "", ""], correct_index: 0 }; const [form, setForm] = useState(blank);
  const load = () => db.from("questions").select("*").eq("exam_id", exam.id).order("q_order").then(({ data }: any) => setQuestions(data ?? [])); useEffect(() => { load(); }, [exam.id]);
  const add = async () => { const options = form.question_type === "essay" ? [] : form.options.filter(Boolean); if (!form.prompt || (form.question_type === "multiple_choice" && options.length < 2)) return toast.error(tx("أكمل بيانات السؤال", "Complete question details")); const image_url = image ? await uploadFile("media", "questions", image) : null; const { error } = await db.from("questions").insert({ exam_id: exam.id, prompt: form.prompt, question_type: form.question_type, points: form.points, options, correct_index: form.correct_index, image_url, q_order: questions.length + 1 }); if (error) return toast.error(error.message); setForm(blank); setImage(null); load(); };
  return <div className="grid gap-5 lg:grid-cols-2"><Card className="space-y-3 border-primary/30"><div className="flex justify-between gap-2"><h3 className="font-bold">{exam.title}</h3><Button variant="ghost" onClick={back}>{tx("رجوع", "Back")}</Button></div><select className={selectClass} value={form.question_type} onChange={(e) => setForm({ ...form, question_type: e.target.value })}><option value="multiple_choice">{tx("اختيار من متعدد", "Multiple choice")}</option><option value="essay">{tx("سؤال مقالي", "Essay")}</option></select><Input value={form.prompt} onChange={(e) => setForm({ ...form, prompt: e.target.value })} placeholder={tx("نص السؤال", "Question text")} /><div><Label>{tx("درجة السؤال", "Question points")}</Label><Input type="number" min="1" value={form.points} onChange={(e) => setForm({ ...form, points: +e.target.value })} /></div><div><Label>{tx("صورة اختيارية", "Optional image")}</Label><Input type="file" accept="image/*" onChange={(e) => setImage(e.target.files?.[0] ?? null)} /></div>{form.question_type === "multiple_choice" && form.options.map((option, index) => <div key={index} className="flex items-center gap-2"><input type="radio" checked={form.correct_index === index} onChange={() => setForm({ ...form, correct_index: index })} /><Input value={option} onChange={(e) => { const options = [...form.options]; options[index] = e.target.value; setForm({ ...form, options }); }} placeholder={`${tx("اختيار", "Option")} ${index + 1}`} /></div>)}<Button onClick={add}>{tx("إضافة السؤال", "Add question")}</Button></Card><Card><h3 className="mb-4 font-bold">{tx("أسئلة الامتحان", "Exam questions")} ({questions.length})</h3>{questions.map((q, index) => <div key={q.id} className="flex items-start gap-3 border-t py-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-md bg-primary/15 font-bold text-primary">{index + 1}</span><div className="flex-1"><p className="font-semibold">{q.prompt}</p><p className="mt-1 text-xs text-muted-foreground">{q.question_type === "essay" ? tx("مقالي", "Essay") : tx("اختيار من متعدد", "Multiple choice")} · {q.points} {tx("درجة", "points")}</p></div><Button size="icon" variant="ghost" aria-label={tx("حذف", "Delete")} onClick={async () => { await db.from("questions").delete().eq("id", q.id); load(); }}><Trash2 className="h-4 w-4 text-destructive" /></Button></div>)}</Card></div>;
}