import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, ClipboardList, FilePenLine, Hourglass, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Bubbles } from "@/components/site/Bubbles";
import { Card, db, QImage } from "@/components/site/shared";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useApp } from "@/lib/app-context";

function ExamSession({ exam, attempt, back }: { exam: any; attempt: any; back: () => void }) {
  const { tx } = useApp();
  const [questions, setQuestions] = useState<any[]>([]), [answers, setAnswers] = useState<Record<string, number | string>>({}), [saved, setSaved] = useState<Record<string, number | string>>({});
  const review = Boolean(attempt && exam.is_closed);
  useEffect(() => { db.rpc(review ? "get_exam_review" : "get_exam_questions", { _exam_id: exam.id }).then(({ data }: any) => setQuestions(data ?? [])); if (attempt) db.from("attempts").select("answers").eq("exam_id", exam.id).maybeSingle().then(({ data }: any) => setSaved(data?.answers ?? {})); }, [exam.id, review]);
  const submit = async () => { const { data, error } = await db.rpc("submit_attempt", { _exam_id: exam.id, _answers: answers }); if (error || !data?.ok) return toast.error(error?.message ?? tx("تم التسليم من قبل", "Already submitted")); toast.success(data.grading_status === "pending" ? tx("تم التسليم — السؤال المقالي بانتظار التصحيح", "Submitted — essay awaits grading") : `${tx("درجتك", "Your score")}: ${data.score}/${data.total}`); back(); };
  const complete = questions.length > 0 && questions.every((q) => answers[q.id] !== undefined && String(answers[q.id]).trim() !== "");
  return <Card className="relative overflow-hidden border-primary/40"><Bubbles count={5} /><div className="relative z-10"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold text-primary">RESEARCHER EXAM</p><h2 className="text-2xl font-black">{exam.title}</h2></div><Button variant="ghost" onClick={back}><ArrowRight className="h-4 w-4" />{tx("رجوع", "Back")}</Button></div>
    <div className="space-y-5">{questions.map((q, i) => <div key={q.id} className="rounded-lg border border-primary/25 bg-background/70 p-5 transition hover:border-primary/60"><div className="mb-3 flex items-start justify-between gap-3"><p className="font-bold">{i + 1}. {q.prompt}</p><span className="shrink-0 rounded-md bg-primary/15 px-2 py-1 text-xs font-bold text-primary">{q.points} {tx("درجة", "pts")}</span></div><QImage path={q.image_url} />
      {q.question_type === "essay" ? <Textarea disabled={review || Boolean(attempt)} value={String((review || attempt ? saved[q.id] : answers[q.id]) ?? "")} onChange={(e) => setAnswers({ ...answers, [q.id]: e.target.value })} placeholder={tx("اكتب إجابتك المقالية بالتفصيل…", "Write your essay answer…")} className="mt-3 min-h-36 border-primary/30" /> : <div className="mt-3 grid gap-2">{(q.options as string[]).map((option, j) => { const picked = Number((review ? saved : answers)[q.id]) === j; const state = review ? (j === q.correct_index ? "border-success bg-success/15" : picked ? "border-destructive bg-destructive/15" : "") : picked ? "border-primary bg-primary/15 shadow-gold" : "hover:-translate-y-0.5 hover:border-primary/60 hover:bg-primary/5"; return <Button key={j} type="button" variant="outline" disabled={review || Boolean(attempt)} onClick={() => setAnswers({ ...answers, [q.id]: j })} className={`h-auto min-h-12 justify-start whitespace-normal p-3 text-start transition ${state}`}>{option}</Button>; })}</div>}
    </div>)}</div>
    {!attempt && <Button size="lg" disabled={!complete} onClick={submit} className="mt-6 w-full md:w-auto"><CheckCircle2 className="h-5 w-5" />{tx("تسليم الامتحان", "Submit exam")}</Button>}
    {attempt?.grading_status === "pending" && <p className="mt-5 flex items-center gap-2 rounded-lg bg-primary/10 p-4 text-sm text-primary"><Hourglass className="h-5 w-5" />{tx("إجابتك المقالية تحت المراجعة، وستظهر الدرجة النهائية بعد التصحيح.", "Your essay is being reviewed; the final grade will appear after grading.")}</p>}
  </div></Card>;
}

export function StudentExams() {
  const { tx } = useApp();
  const [folders, setFolders] = useState<any[]>([]), [exams, setExams] = useState<any[]>([]), [attempts, setAttempts] = useState<any[]>([]), [open, setOpen] = useState<any>(null);
  const load = async () => { const [f, e, a] = await Promise.all([db.from("folders").select("*").order("created_at"), db.from("exams").select("*").order("created_at"), db.from("attempts").select("exam_id,score,total,grading_status")]); setFolders(f.data ?? []); setExams(e.data ?? []); setAttempts(a.data ?? []); };
  useEffect(() => { load(); }, []);
  if (open) return <ExamSession exam={open} attempt={attempts.find((a) => a.exam_id === open.id)} back={() => { setOpen(null); load(); }} />;
  const groups = [...folders, { id: null, title: tx("اختبارات عامة", "General exams") }];
  return <div className="space-y-8">{groups.map((folder) => { const list = exams.filter((e) => e.folder_id === folder.id); if (!list.length) return null; return <section key={folder.id ?? "general"}><div className="mb-4 flex items-center gap-3"><div className="icon-tile"><ClipboardList className="h-5 w-5" /></div><h2 className="text-xl font-black text-primary">{folder.title}</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map((exam) => { const attempt = attempts.find((a) => a.exam_id === exam.id); return <Card key={exam.id} className="group relative overflow-hidden border-primary/30 transition hover:-translate-y-1 hover:border-primary/70 hover:shadow-gold"><div className="absolute end-4 top-4 text-primary/20 transition group-hover:rotate-6 group-hover:text-primary/40"><FilePenLine className="h-16 w-16" /></div><Sparkles className="mb-5 h-5 w-5 animate-[icon-float_3s_ease-in-out_infinite] text-primary" /><h3 className="relative text-lg font-black">{exam.title}</h3><p className="relative mt-2 text-sm text-muted-foreground">{attempt ? (attempt.grading_status === "pending" ? tx("بانتظار التصحيح المقالي", "Awaiting essay grading") : `${tx("النتيجة", "Score")}: ${attempt.score}/${attempt.total}`) : tx("جاهز للبدء", "Ready to begin")}</p><Button className="relative mt-5 w-full" variant={attempt ? "outline" : "default"} disabled={Boolean(attempt && !exam.is_closed)} onClick={() => setOpen(exam)}>{attempt ? (exam.is_closed ? tx("مراجعة الإجابات", "Review answers") : tx("تم التسليم", "Submitted")) : tx("ابدأ الامتحان", "Start exam")}</Button></Card>; })}</div></section>; })}</div>;
}